# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: normalization.proto
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="normalization.proto",
    package="normalization",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\x13normalization.proto\x12\rnormalization"\x17\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t2U\n\rNormalization\x12\x44\n\x10GetNormalization\x12\x16.normalization.Message\x1a\x16.normalization.Message"\x00\x62\x06proto3',
)


_MESSAGE = _descriptor.Descriptor(
    name="Message",
    full_name="normalization.Message",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="text",
            full_name="normalization.Message.text",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=38,
    serialized_end=61,
)

DESCRIPTOR.message_types_by_name["Message"] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType(
    "Message",
    (_message.Message,),
    {
        "DESCRIPTOR": _MESSAGE,
        "__module__": "normalization_pb2"
        # @@protoc_insertion_point(class_scope:normalization.Message)
    },
)
_sym_db.RegisterMessage(Message)


_NORMALIZATION = _descriptor.ServiceDescriptor(
    name="Normalization",
    full_name="normalization.Normalization",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=63,
    serialized_end=148,
    methods=[
        _descriptor.MethodDescriptor(
            name="GetNormalization",
            full_name="normalization.Normalization.GetNormalization",
            index=0,
            containing_service=None,
            input_type=_MESSAGE,
            output_type=_MESSAGE,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_NORMALIZATION)

DESCRIPTOR.services_by_name["Normalization"] = _NORMALIZATION

# @@protoc_insertion_point(module_scope)
