# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import normalization_pb2 as normalization__pb2


class NormalizationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetNormalization = channel.unary_unary(
        '/normalization.Normalization/GetNormalization',
        request_serializer=normalization__pb2.Message.SerializeToString,
        response_deserializer=normalization__pb2.Message.FromString,
        )


class NormalizationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetNormalization(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NormalizationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetNormalization': grpc.unary_unary_rpc_method_handler(
          servicer.GetNormalization,
          request_deserializer=normalization__pb2.Message.FromString,
          response_serializer=normalization__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'normalization.Normalization', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
